baseurl = "https://lubabuya.github.io/"
theme = "hugo-geo"
#themesdir = "../.."
relativeURLs = true
languageCode = "en-us"
title = ""
disqusShortname = "shortcode-here"
googleAnalytics = "UA-114322442-1" #Google Analytics ID
paginate = 5


[taxonomies]
	tag = "tags"
	tutorial = "tutorials"

[params]
	showglobe = true	
	analytics = "code-here"
	#email = "luba.buya@gmail.com"
	profilepic = "img/profile.jpeg"
	title = ""
	subtitle = "Scattered projects and ideas"

	[[params.socialbuttons]]
	faicon = "github"
	url = "https://github.com/LubaBuya/blog"
	
